# site name
prefixName: 
siteName: たくさん
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: /img/base/avatar.jpg
url: https://www.yeahme.cn
description: Future is comming!
cdn: https://cdn.jsdelivr.net/gh/bruceting/blogcdn
pjax: 1
# 1开启
mathjax: 0

notice: duoduo博客正在开发中...
lazyloadImg: https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/loader/cup.gif

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/tech/, fa: fa-code }, 
    生活: {path: /categories/life/, fa: fa-file-text-o }, 
    随想: {path: /categories/thought/, fa: fa-commenting-o },
    资源: {path: /categories/source/, fa: fa-cloud-download },
    转载: {path: /categories/reprint/, fa: fa-book }
  } }
#  标签: { path: /tags/, fa: fa-tags, submenus: {
#    Java      : {path: /java/, fa: fa-coffee },
#    Spring    : {path: /spring/, fa: fa-leaf },
#    Springboot: {path: /springboot/, fa: fa-envira }
#  } }
#  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: {
    我？: {path: /about/, fa: fa-meetup},
    RSS: { path: /atom.xml, fa: fa-rss faa-pulse }
  } }
#  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
#    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
#    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
#    歌单: {path: /music/, fa: fa-headphones },
#    图集: {path: /tags/图集/, fa: fa-photo }
#  } }
#  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
#  友人帐: { path: /links/, fa: fa-link faa-shake }
#  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
#  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
#    我？: {path: /about/, fa: fa-meetup}, 
#    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
#    Lab: {path: /lab/, fa: fa-cogs },
#  } }
#  客户端: { path: /client/, fa: fa-android faa-vertical }
#  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(1).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(2).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(3).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(4).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(5).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(6).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(7).jpg.webp
  - https://cdn.jsdelivr.net/gh/bruceting/blogcdn/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: /, title: 多多的温馨小屋, desc: 一切尽在掌握中, img: /img/startdash/warmhouse.jpeg}
  - {url: /, title: 小屁孩, desc: It's so cute, img: /img/startdash/baby.jpeg}
  - {url: /, title: 多多的科技屋, desc: 未来由你改变, img: /img/startdash/techhouse.jpeg}



# your site build time or founded date
siteBuildingTime: 21/10/2019

#social  url, img PC端配置
social:
  github: {url: http://github.com/BruceTing, img: /img/social/github.png}
#  sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
#  wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
#  zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
#  email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
#  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/BruceTing, fa: fa-github, color: 333}
#  weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
#  paypal: https://www.paypal.me/hojuncn
  alipay: /img/donate/alipay.jpg
  wechat: /img/donate/wechat.jpg
#  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

